jobs:
  # Job to build and test the user-service Docker image
  user-service:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build User Service Docker image
        run: |
          docker build -t user-service ./user-service

  # Job to build and test the order-service Docker image
  order-service:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Order Service Docker image
        run: |
          docker build -t order-service ./order-service

  # Job to build and test the API Gateway Docker image
  api-gateway:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build API Gateway Docker image
        run: |
          docker build -t api-gateway ./gateway
