name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline when there's a PR to the main branch

jobs:
  # Job to build and test the user-service
  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies for User Service
        run: |
          cd user-service
          npm install
      - name: Run Tests for User Service
        run: |
          cd user-service
          npm test

  # Job to build and test the order-service
  order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies for Order Service
        run: |
          cd order-service
          npm install
      - name: Run Tests for Order Service
        run: |
          cd order-service
          npm test

  # Job to build and test the API Gateway
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies for API Gateway
        run: |
          cd gateway
          npm install
      - name: Run Tests for API Gateway
        run: |
          cd gateway
          npm test
