name: Build and Publish Images to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch: # Keeps the manual trigger option as well


jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build images
        run: |
          docker build ./user-service -t chamaththa/user-service:latest
          
          docker build ./order-service -t chamaththa/order-service:latest
          
          docker build ./gateway -t chamaththa/api-gateway:latest

      - name: Push images to Docker Hub t
        run: |
          docker login -u chamaththa -p ${{ secrets.DOCKER_HUB_TOKEN }}
          
          docker push chamaththa/user-service:latest
          
          docker push chamaththa/order-service:latest
          
          docker push chamaththa/api-gateway:latest
