name: Build and Publish Images to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push User Service
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: chamaththa/user-service:latest

      - name: Build and Push Order Service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: true
          tags: chamaththa/order-service:latest

      - name: Build and Push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: chamaththa/api-gateway:latest
